import { Roboto } from "next/font/google";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "700"] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={roboto.className} lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
